-- =============================================================================
-- PEF · 002_seed_catalogs.sql
-- Closed-value catalogs + initial privacy notice version.
--
-- SCOPE: all environments, including production. Boot requirement: without
-- these rows the system cannot create an operation or a session.
--
-- IDEMPOTENT: uses ON CONFLICT (code) DO UPDATE so it can re-run after adding
-- new values without duplicating or breaking references.
-- Identifiers are generated by default; cross-table references resolve by
-- `code`, never by literal UUID.
--
-- LANGUAGE: `code` is the stable English identifier used in MongoDB and
-- integrations. `name` is display text (English for the demo UI locale).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Minimal patient demographics
-- -----------------------------------------------------------------------------
INSERT INTO cat_gender (code, name) VALUES
  ('female',  'Female'),
  ('male',    'Male'),
  ('other',   'Other'),
  ('unknown', 'Unspecified')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Medical specialty
-- -----------------------------------------------------------------------------
INSERT INTO cat_specialty (code, name) VALUES
  ('general_surgery',  'General surgery'),
  ('orthopedics',      'Orthopedics and trauma'),
  ('gynecology',       'Gynecology and obstetrics'),
  ('urology',          'Urology'),
  ('neurosurgery',     'Neurosurgery'),
  ('anesthesiology',   'Anesthesiology')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Surgical procedure type
-- Institution-defined catalog. Values here are a representative starting set.
-- -----------------------------------------------------------------------------
INSERT INTO cat_procedure_type (code, name) VALUES
  ('lap_chole',      'Laparoscopic cholecystectomy'),
  ('open_chole',     'Open cholecystectomy'),
  ('appendectomy',   'Appendectomy'),
  ('hernia_repair',  'Inguinal hernia repair'),
  ('cesarean',       'Cesarean section'),
  ('hip_replace',    'Hip arthroplasty')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Physician role in the surgical act
-- -----------------------------------------------------------------------------
INSERT INTO cat_surgical_role (code, name) VALUES
  ('surgeon',         'Surgeon'),
  ('first_assistant', 'First assistant'),
  ('anesthesiologist','Anesthesiologist'),
  ('resident',        'Resident physician')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Operation status
-- -----------------------------------------------------------------------------
INSERT INTO cat_operation_status (code, name) VALUES
  ('scheduled',   'Scheduled'),
  ('in_progress', 'In progress'),
  ('closed',      'Closed'),
  ('cancelled',   'Cancelled')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Counting session status (RF state machine)
--   scheduled -> in_progress -> awaiting_spd_review|correction_required -> closed
--   any eligible state -> aborted
-- -----------------------------------------------------------------------------
INSERT INTO cat_session_status (code, name) VALUES
  ('scheduled',           'Scheduled'),
  ('in_progress',         'In progress'),
  ('awaiting_spd_review', 'Awaiting SPD review'),
  ('correction_required', 'Correction required'),
  ('closed',              'Closed'),
  ('aborted',             'Aborted')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Instrument piece lifecycle
-- -----------------------------------------------------------------------------
INSERT INTO cat_instrument_cycle_status (code, name) VALUES
  ('available',     'Available'),
  ('reserved',      'Reserved'),
  ('in_use',        'In use'),
  ('sterilization', 'Sterilization'),
  ('maintenance',   'Maintenance'),
  ('retired',       'Retired'),
  ('lost',          'Lost / not recovered')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Functional category of the instrument family (UI Type filter / kit blocks)
-- Order used in composition: Cutting → Dissection → Grasping → Hemostasis →
-- Retraction → Suction → Suturing
-- -----------------------------------------------------------------------------
INSERT INTO cat_instrument_category (code, name) VALUES
  ('cutting',    'Cutting'),
  ('dissection', 'Dissection'),
  ('grasping',   'Grasping'),
  ('hemostasis', 'Hemostasis'),
  ('retraction', 'Retraction'),
  ('suction',    'Suction'),
  ('suturing',   'Suturing')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Instrument usage context
-- -----------------------------------------------------------------------------
INSERT INTO cat_usage_context (code, name) VALUES
  ('operative',   'Operative use in a surgical procedure'),
  ('pedagogical', 'Pedagogical or training use')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Discrepancy typing
-- -----------------------------------------------------------------------------
INSERT INTO cat_discrepancy_reason (code, name) VALUES
  ('shortage',        'Shortage versus expected inventory'),
  ('surplus',         'Surplus versus expected inventory'),
  ('unidentified',    'Present piece not identified by the model'),
  ('occluded',        'Piece occluded or outside the region of interest'),
  ('misclassified',   'Piece classified into the wrong family'),
  ('operator_error',  'Capture or operator handling error')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Visual evidence capture reason
-- These codes are the allowed values of `reason` in MongoDB checkpoint_frame.
-- See PEF-DS06.
-- -----------------------------------------------------------------------------
INSERT INTO cat_checkpoint_reason (code, name) VALUES
  ('start',        'Session start'),
  ('close',        'Session close'),
  ('hourly',       'Periodic capture'),
  ('state_change', 'Relevant state change'),
  ('discrepancy',  'Discrepancy recorded'),
  ('manual_pin',   'Manual operator pin')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Surgical / counting phase
-- These codes are the allowed values of `phase_code` in MongoDB checkpoint_frame.
--
-- WARNING: this list needs clinical validation before production.
-- The sequence for each procedure is configured in procedure_phase, not here:
-- this catalog only declares which phases exist.
-- -----------------------------------------------------------------------------
INSERT INTO cat_operation_phase (code, name, active) VALUES
  ('start',        'Start / initial stage', TRUE),
  ('demo_phase_1', 'Demo phase one',        TRUE),
  ('demo_phase_2', 'Demo phase two',        TRUE),
  ('demo_phase_3', 'Demo phase three',      TRUE),
  ('final_count',  'Final count',           TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Count-event vocabulary
-- Domain of count_event.event_type_id.
-- -----------------------------------------------------------------------------
INSERT INTO cat_event_type (code, name) VALUES
  ('session_open',       'Session open'),
  ('auto_count',         'Model-suggested count'),
  ('manual_count',       'Manually captured count'),
  ('manual_close',       'Close with manual quantity report'),
  ('phase_change',       'Surgical phase change'),
  ('discrepancy_raised', 'Discrepancy detected'),
  ('correction_applied', 'Human correction applied'),
  ('validation_passed',  'Validation with no discrepancies'),
  ('close_blocked',      'Close attempt blocked'),
  ('session_close',      'Session close')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Personal-data processing purposes (LFPDPPP / GDPR)
-- The three codes are fixed by CHECK in the schema; new purposes need a migration.
-- -----------------------------------------------------------------------------
INSERT INTO cat_processing_purpose (code, name, active) VALUES
  ('quality_ops',       'Quality and operations of the counting process', TRUE),
  ('model_improvement', 'Vision model improvement',                       TRUE),
  ('external_sharing',  'Transfer to third parties',                      TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Initial privacy notice version (PLACEHOLDER demo)
--
-- document_uri / content_sha256 are NOT a real legal PDF. They exercise RF
-- usability (confirm notice, quality_ops / model_improvement purposes, or
-- session without notice → manual_no_privacy). Replace before real data.
-- -----------------------------------------------------------------------------
INSERT INTO privacy_notice_version (version, effective_at, document_uri, content_sha256, active)
VALUES (
  'v1.0',
  '2026-09-01T00:00:00Z',
  'placeholder://privacy-notice/v1.0',
  repeat('0', 64),
  TRUE
)
ON CONFLICT (version) DO NOTHING;

COMMIT;

-- -----------------------------------------------------------------------------
-- Post-load verification
-- -----------------------------------------------------------------------------
-- SELECT 'cat_gender' AS catalog, count(*) FROM cat_gender
-- UNION ALL SELECT 'cat_specialty', count(*) FROM cat_specialty
-- UNION ALL SELECT 'cat_procedure_type', count(*) FROM cat_procedure_type
-- UNION ALL SELECT 'cat_surgical_role', count(*) FROM cat_surgical_role
-- UNION ALL SELECT 'cat_operation_status', count(*) FROM cat_operation_status
-- UNION ALL SELECT 'cat_session_status', count(*) FROM cat_session_status
-- UNION ALL SELECT 'cat_instrument_cycle_status', count(*) FROM cat_instrument_cycle_status
-- UNION ALL SELECT 'cat_instrument_category', count(*) FROM cat_instrument_category
-- UNION ALL SELECT 'cat_usage_context', count(*) FROM cat_usage_context
-- UNION ALL SELECT 'cat_discrepancy_reason', count(*) FROM cat_discrepancy_reason
-- UNION ALL SELECT 'cat_checkpoint_reason', count(*) FROM cat_checkpoint_reason
-- UNION ALL SELECT 'cat_operation_phase', count(*) FROM cat_operation_phase
-- UNION ALL SELECT 'cat_event_type', count(*) FROM cat_event_type
-- UNION ALL SELECT 'cat_processing_purpose', count(*) FROM cat_processing_purpose
-- ORDER BY 1;
