-- =============================================================================
-- PEF · 002_seed_catalogs.sql
-- Closed-value catalogs + initial privacy notice version.
--
-- SCOPE: every environment, production included. Required at startup: without
-- these rows the system cannot create an operation or a counting session.
--
-- IDEMPOTENT: uses ON CONFLICT (code) DO UPDATE, so it can be re-run after new
-- values are added without duplicating rows or breaking references. Ids are
-- generated by default; references between tables are always resolved by
-- `code`, never by a literal UUID.
--
-- LANGUAGE: English is the canonical language for persisted database business
-- data and catalog data. `code` is the stable identifier used by the
-- application, MongoDB and integrations; `name` is the canonical English
-- display value. UI localization (e.g. Spanish) is handled at the application
-- layer, not by storing translated copies in the database.
-- Existing databases seeded with the former Spanish names are converted by
-- data/migrations/005_canonical_english_data.sql.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Minimal patient demographics
-- -----------------------------------------------------------------------------
INSERT INTO cat_gender (code, name) VALUES
  ('female',  'Female'),
  ('male',    'Male'),
  ('other',   'Other'),
  ('unknown', 'Unspecified')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Medical specialty
-- -----------------------------------------------------------------------------
INSERT INTO cat_specialty (code, name) VALUES
  ('general_surgery',  'General Surgery'),
  ('orthopedics',      'Orthopedics and Traumatology'),
  ('gynecology',       'Gynecology and Obstetrics'),
  ('urology',          'Urology'),
  ('neurosurgery',     'Neurosurgery'),
  ('anesthesiology',   'Anesthesiology')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Surgical procedure type
-- Institution-defined catalog. These values are a representative starting
-- point and are extended per hospital.
-- -----------------------------------------------------------------------------
INSERT INTO cat_procedure_type (code, name) VALUES
  ('lap_chole',      'Laparoscopic Cholecystectomy'),
  ('open_chole',     'Open Cholecystectomy'),
  ('appendectomy',   'Appendectomy'),
  ('hernia_repair',  'Inguinal Hernia Repair'),
  ('cesarean',       'Cesarean Section'),
  ('hip_replace',    'Hip Arthroplasty')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Physician role in the surgical act
-- -----------------------------------------------------------------------------
INSERT INTO cat_surgical_role (code, name) VALUES
  ('surgeon',         'Surgeon'),
  ('first_assistant', 'First Assistant'),
  ('anesthesiologist','Anesthesiologist'),
  ('resident',        'Resident Physician')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Operation status
-- -----------------------------------------------------------------------------
INSERT INTO cat_operation_status (code, name) VALUES
  ('scheduled',   'Scheduled'),
  ('in_progress', 'In Progress'),
  ('closed',      'Closed'),
  ('cancelled',   'Cancelled')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Counting session status (state machine)
--   open -> counting -> validating -> closed
--   any state -> cancelled
-- `blocked` represents a session with unresolved discrepancies that cannot be
-- closed; it is where the business rule stops the flow.
-- -----------------------------------------------------------------------------
INSERT INTO cat_session_status (code, name) VALUES
  ('open',       'Open'),
  ('counting',   'Counting'),
  ('validating', 'Validating'),
  ('blocked',    'Blocked by Discrepancy'),
  ('closed',     'Closed'),
  ('cancelled',  'Cancelled')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Instrument piece life cycle
-- -----------------------------------------------------------------------------
INSERT INTO cat_instrument_cycle_status (code, name) VALUES
  ('available',     'Available'),
  ('reserved',      'Reserved'),
  ('in_use',        'In Use'),
  ('sterilization', 'In Sterilization'),
  ('maintenance',   'In Maintenance'),
  ('retired',       'Retired')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Functional category of an instrument family
-- -----------------------------------------------------------------------------
INSERT INTO cat_instrument_category (code, name) VALUES
  ('hemostasis', 'Hemostasis'),
  ('cutting',    'Cutting'),
  ('dissection', 'Dissection'),
  ('retraction', 'Retraction'),
  ('grasping',   'Grasping'),
  ('suturing',   'Suturing'),
  ('suction',    'Suction')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Instrument usage context
-- -----------------------------------------------------------------------------
INSERT INTO cat_usage_context (code, name) VALUES
  ('operative',   'Operative use during surgery'),
  ('pedagogical', 'Teaching or training use')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Discrepancy reason
-- -----------------------------------------------------------------------------
INSERT INTO cat_discrepancy_reason (code, name) VALUES
  ('shortage',        'Shortage against expected inventory'),
  ('surplus',         'Surplus against expected inventory'),
  ('unidentified',    'Item present but not identified by the model'),
  ('occluded',        'Item occluded or outside the region of interest'),
  ('misclassified',   'Item classified into the wrong family'),
  ('operator_error',  'Operator capture or handling error'),
  ('low_confidence',  'Model confidence below threshold')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Visual evidence capture reason
-- These codes are the allowed values of the `reason` field of the MongoDB
-- checkpoint_frame collection. See PEF-DS06.
-- -----------------------------------------------------------------------------
INSERT INTO cat_checkpoint_reason (code, name) VALUES
  ('start',        'Session start'),
  ('close',        'Session close'),
  ('hourly',       'Periodic capture'),
  ('state_change', 'Relevant state change'),
  ('discrepancy',  'Discrepancy recorded'),
  ('manual_pin',   'Operator manual pin')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Surgical / counting phase
-- These codes are the allowed values of the `phase_code` field of the MongoDB
-- checkpoint_frame collection.
--
-- WARNING: this list requires clinical validation before production. The
-- sequence applicable to each procedure is configured in procedure_phase, not
-- here: this catalog only declares which phases exist.
-- -----------------------------------------------------------------------------
INSERT INTO cat_operation_phase (code, name, active) VALUES
  ('setup',        'Table Setup',                      TRUE),
  ('pre_incision', 'Initial Count Before Incision',    TRUE),
  ('intraop',      'Intraoperative',                   TRUE),
  ('pre_closure',  'Count Before Cavity Closure',      TRUE),
  ('closure',      'Closure',                          TRUE),
  ('final_count',  'Final Count',                      TRUE),
  ('handover',     'Tray Handover and Removal',        TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Count event vocabulary
-- Domain of count_event.event_type_id.
-- -----------------------------------------------------------------------------
INSERT INTO cat_event_type (code, name) VALUES
  ('session_open',       'Session opened'),
  ('auto_count',         'Model-suggested count'),
  ('manual_count',       'Manual count'),
  ('phase_change',       'Surgical phase change'),
  ('discrepancy_raised', 'Discrepancy raised'),
  ('correction_applied', 'Human correction applied'),
  ('validation_passed',  'Validation without discrepancies'),
  ('close_blocked',      'Close attempt blocked'),
  ('session_close',      'Session closed'),
  ('correction_requested', 'Correction requested by supervisor')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Personal data processing purposes (LFPDPPP / GDPR)
-- The three codes are fixed by a CHECK constraint in the schema; new purposes
-- cannot be added without a migration.
-- -----------------------------------------------------------------------------
INSERT INTO cat_processing_purpose (code, name, active) VALUES
  ('quality_ops',       'Counting process quality and operations', TRUE),
  ('model_improvement', 'Vision model improvement',                TRUE),
  ('external_sharing',  'Third-party data sharing',                TRUE)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- Initial privacy notice version
--
-- PENDING: replace document_uri and content_sha256 with the real values of the
-- notice approved by the institution before any deployment with data of real
-- people. The hash must match the published document.
-- -----------------------------------------------------------------------------
INSERT INTO privacy_notice_version (version, effective_at, document_uri, content_sha256, active)
VALUES (
  'v1.0',
  '2026-09-01T00:00:00Z',
  'https://pef.udem/overhead-count/privacy-notice/v1.0',
  repeat('0', 64),
  TRUE
)
ON CONFLICT (version) DO NOTHING;

COMMIT;

-- -----------------------------------------------------------------------------
-- Post-load verification
-- -----------------------------------------------------------------------------
-- SELECT 'cat_gender' AS catalog, count(*) FROM cat_gender
-- UNION ALL SELECT 'cat_specialty', count(*) FROM cat_specialty
-- UNION ALL SELECT 'cat_procedure_type', count(*) FROM cat_procedure_type
-- UNION ALL SELECT 'cat_surgical_role', count(*) FROM cat_surgical_role
-- UNION ALL SELECT 'cat_operation_status', count(*) FROM cat_operation_status
-- UNION ALL SELECT 'cat_session_status', count(*) FROM cat_session_status
-- UNION ALL SELECT 'cat_instrument_cycle_status', count(*) FROM cat_instrument_cycle_status
-- UNION ALL SELECT 'cat_instrument_category', count(*) FROM cat_instrument_category
-- UNION ALL SELECT 'cat_usage_context', count(*) FROM cat_usage_context
-- UNION ALL SELECT 'cat_discrepancy_reason', count(*) FROM cat_discrepancy_reason
-- UNION ALL SELECT 'cat_checkpoint_reason', count(*) FROM cat_checkpoint_reason
-- UNION ALL SELECT 'cat_operation_phase', count(*) FROM cat_operation_phase
-- UNION ALL SELECT 'cat_event_type', count(*) FROM cat_event_type
-- UNION ALL SELECT 'cat_processing_purpose', count(*) FROM cat_processing_purpose
-- ORDER BY 1;
